name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag my-image-name:$(date +%s)
       docker images

    - name: docker run 
      run: docker run -p 8888:8888 my-image-name:$(date +%s)
